#!/usr/bin/env bash
# ───────────────────────────────────────────────────────────────────────────
# CubeSandbox DNS 转发配置（生产机一次性执行，需 root）。
#
# 作用：让 docker 容器内能解析 sandbox 域名（形如 <id>.cube.app → 192.168.10.136）。
#   docker 内嵌 DNS(127.0.0.11) 只解 appnet 服务名；外部域名转发给 daemon.json 的
#   "dns" 上游。本脚本：
#     1) 安装/检测 dnsmasq，写入 /etc/dnsmasq.d/cube.conf：
#          server=/cube.app/192.168.10.136     # *.cube.app 转发到 CubeSandbox DNS
#          listen-address=172.17.0.1,127.0.0.1 # docker0 网关，供容器经 daemon dns 访问
#     2) /etc/docker/daemon.json 增加 "dns": ["172.17.0.1"]（保留原有键，先备份）
#     3) 重启 dnsmasq + docker，并验证容器内解析。
#
# 为什么不用 compose 的 dns: 字段：它会顶掉 127.0.0.11，导致 agent/mcp 无法用
#   appnet 服务名互访；daemon 级 dns 保留内嵌 DNS，仅转发外部域名。
#
# 用法：
#   sudo bash deploy/setup-cube-dns.sh
#   CUBE_SANDBOX_IP=192.168.10.136 bash deploy/setup-cube-dns.sh   # 覆盖 sandbox IP
#   CUBE_DOMAIN=cube.app bash deploy/setup-cube-dns.sh             # 覆盖域名后缀
# ───────────────────────────────────────────────────────────────────────────
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "[错误] 需要 root：sudo bash $0" >&2
  exit 1
fi

CUBE_SANDBOX_IP="${CUBE_SANDBOX_IP:-192.168.10.136}"
CUBE_DOMAIN="${CUBE_DOMAIN:-cube.app}"
DNSMASQ_LISTEN="${DNSMASQ_LISTEN:-172.17.0.1}"

echo "==> 1/4 检测 dnsmasq"
if ! command -v dnsmasq >/dev/null 2>&1; then
  echo "    dnsmasq 未安装，尝试安装..."
  if command -v dnf >/dev/null 2>&1; then dnf install -y dnsmasq
  elif command -v yum >/dev/null 2>&1; then yum install -y dnsmasq
  elif command -v apt-get >/dev/null 2>&1; then apt-get update && apt-get install -y dnsmasq
  else echo "[错误] 无法自动安装 dnsmasq，请手动安装后重跑" >&2; exit 1; fi
fi

echo "==> 2/4 写入 /etc/dnsmasq.d/cube.conf"
mkdir -p /etc/dnsmasq.d
cat > /etc/dnsmasq.d/cube.conf <<EOF
# generated by deploy/setup-cube-dns.sh — CubeSandbox 域名转发
server=/$CUBE_DOMAIN/$CUBE_SANDBOX_IP
listen-address=$DNSMASQ_LISTEN,127.0.0.1
bind-interfaces
EOF
echo "    server=/$CUBE_DOMAIN/$CUBE_SANDBOX_IP"

echo "==> 3/4 配置 /etc/docker/daemon.json（备份原文件）"
DAEMON_JSON=/etc/docker/daemon.json
if [[ -f "$DAEMON_JSON" ]]; then
  cp -a "$DAEMON_JSON" "${DAEMON_JSON}.bak.$(date +%Y%m%d%H%M%S)"
fi
if ! command -v python3 >/dev/null 2>&1; then
  echo "[错误] 需要 python3 来合并 daemon.json，请安装后重跑" >&2
  exit 1
fi
python3 - "$DAEMON_JSON" "$DNSMASQ_LISTEN" <<'PYEOF'
import json, sys
path, dns = sys.argv[1], sys.argv[2]
try:
    with open(path, encoding="utf-8") as f:
        cfg = json.load(f)
except (FileNotFoundError, json.JSONDecodeError):
    cfg = {}
cfg["dns"] = [dns]
with open(path, "w", encoding="utf-8") as f:
    json.dump(cfg, f, indent=2)
    f.write("\n")
print(f"    daemon.json dns = [{dns}]，原有其它键保留")
PYEOF

echo "==> 4/4 重启 dnsmasq + docker 并验证"
systemctl enable --now dnsmasq >/dev/null 2>&1 || service dnsmasq restart >/dev/null 2>&1 || true
systemctl restart docker

echo "    验证容器内解析（docker0 网关 $DNSMASQ_LISTEN）："
docker run --rm busybox nslookup "test-sandbox.$CUBE_DOMAIN" 2>&1 | head -8 || echo "    （test-sandbox 可能 NXDOMAIN——只要查询到达 192.168.10.136 即说明转发链路通）"
echo
echo "完成。后续 docker compose up 后可用："
echo "  docker exec geesun-agent nslookup <sandbox-id>.$CUBE_DOMAIN"
