#!/usr/bin/env bash
# ───────────────────────────────────────────────────────────────────────────
# CubeSandbox DNS 配置（生产机一次性执行，需 root）。
#
# 作用：让 docker 容器内能解析 sandbox 域名（形如 <port>-<sandbox_id>.cube.app → 172.16.66.13）。
#   docker 内嵌 DNS(127.0.0.11) 只解 appnet 服务名；外部域名转发给 daemon.json 的
#   "dns" 上游。本脚本：
#     1) 检测/安装 dnsmasq，写入 /etc/dnsmasq.d/cube.conf：
#          address=/cube.app/172.16.66.13      # *.cube.app 本地直答（address= 模式）
#          server=<resolv.conf 上游>           # 非 cube.app 域名正常外网解析
#          listen-address=172.17.0.1,127.0.0.1 # docker0 网关，供容器经 daemon dns 访问
#     2) /etc/docker/daemon.json 设置 "dns": ["172.17.0.1"]（保留原有键，先备份）
#     3) 重启 dnsmasq + docker，并验证容器内解析。
#
# ⚠️ 必须用 address= 直答模式，不要用 server=/cube.app/<IP> 转发模式：
#   server= 会把查询转发给 <IP>:53 的 DNS 服务；172.16.66.13 上并无 DNS 服务
#   （实测 53 端口不通），转发必然 NXDOMAIN/超时。address= 由 dnsmasq 本地直答，
#   与 dev 机 WSL 的 /etc/dnsmasq.d/cube.conf 写法一致（2026-09-02 实测修正）。
#
# 为什么不用 compose 的 dns: 字段：它会顶掉 127.0.0.11，导致 agent/mcp 无法用
#   appnet 服务名互访；daemon 级 dns 保留内嵌 DNS，仅转发外部域名。
#
# 用法：
#   sudo bash deploy/setup-cube-dns.sh
#   CUBE_SANDBOX_IP=172.16.66.13 bash deploy/setup-cube-dns.sh  # 覆盖 sandbox IP
#   CUBE_DOMAIN=cube.app bash deploy/setup-cube-dns.sh          # 覆盖域名后缀
# ───────────────────────────────────────────────────────────────────────────
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "[错误] 需要 root：sudo bash $0" >&2
  exit 1
fi

CUBE_SANDBOX_IP="${CUBE_SANDBOX_IP:-172.16.66.13}"
CUBE_DOMAIN="${CUBE_DOMAIN:-cube.app}"
DNSMASQ_LISTEN="${DNSMASQ_LISTEN:-172.17.0.1}"

echo "==> 1/5 检测 dnsmasq"
if ! command -v dnsmasq >/dev/null 2>&1; then
  echo "    dnsmasq 未安装，尝试安装..."
  if command -v dnf >/dev/null 2>&1; then dnf install -y dnsmasq
  elif command -v yum >/dev/null 2>&1; then yum install -y dnsmasq
  elif command -v apt-get >/dev/null 2>&1; then apt-get update && apt-get install -y dnsmasq
  else echo "[错误] 无法自动安装 dnsmasq，请手动安装后重跑" >&2; exit 1; fi
fi

echo "==> 2/5 取宿主机上游 DNS（保持外网解析）"
UPSTREAMS=()
while read -r _ns; do
  [[ -n "$_ns" ]] && UPSTREAMS+=("$_ns")
done < <(grep -E '^\s*nameserver\s+' /etc/resolv.conf 2>/dev/null | awk '{print $2}' | grep -v '^127\.' | grep -v '^::1' || true)
if [[ ${#UPSTREAMS[@]} -eq 0 ]]; then
  echo "    resolv.conf 无可用上游，fallback 8.8.8.8 / 1.1.1.1"
  UPSTREAMS=(8.8.8.8 1.1.1.1)
fi
echo "    上游: ${UPSTREAMS[*]}"

echo "==> 3/5 写入 /etc/dnsmasq.d/cube.conf"
mkdir -p /etc/dnsmasq.d
{
  echo "# generated by deploy/setup-cube-dns.sh — CubeSandbox 域名直答（address= 模式）"
  echo "address=/$CUBE_DOMAIN/$CUBE_SANDBOX_IP"
  echo "# 上游 DNS（保持外网解析）"
  for ns in "${UPSTREAMS[@]}"; do echo "server=$ns"; done
  echo "listen-address=$DNSMASQ_LISTEN,127.0.0.1"
  echo "bind-interfaces"
} > /etc/dnsmasq.d/cube.conf
echo "    address=/$CUBE_DOMAIN/$CUBE_SANDBOX_IP"

echo "==> 4/5 配置 /etc/docker/daemon.json（备份原文件）"
DAEMON_JSON=/etc/docker/daemon.json
if [[ -f "$DAEMON_JSON" ]]; then
  cp -a "$DAEMON_JSON" "${DAEMON_JSON}.bak.$(date +%Y%m%d%H%M%S)"
fi
if ! command -v python3 >/dev/null 2>&1; then
  echo "[错误] 需要 python3 来合并 daemon.json，请安装后重跑" >&2
  exit 1
fi
python3 - "$DAEMON_JSON" "$DNSMASQ_LISTEN" <<'PYEOF'
import json, sys
path, dns = sys.argv[1], sys.argv[2]
try:
    with open(path, encoding="utf-8") as f:
        cfg = json.load(f)
except (FileNotFoundError, json.JSONDecodeError):
    cfg = {}
cfg["dns"] = [dns]
with open(path, "w", encoding="utf-8") as f:
    json.dump(cfg, f, indent=2)
    f.write("\n")
print(f"    daemon.json dns = [{dns}]，原有其它键保留")
PYEOF

echo "==> 5/5 重启 dnsmasq + docker 并验证"
systemctl enable --now dnsmasq >/dev/null 2>&1 || service dnsmasq restart >/dev/null 2>&1 || true
systemctl restart docker

echo "    验证容器内解析（docker0 网关 $DNSMASQ_LISTEN）："
if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
  docker run --rm busybox nslookup "test-sandbox.$CUBE_DOMAIN" 2>&1 | head -8 || \
    echo "    （test-sandbox 可能 NXDOMAIN——只要指向 $CUBE_SANDBOX_IP 即链路通）"
fi
echo
echo "完成。后续 docker compose up 后可用："
echo "  docker exec <agent容器> getent hosts <sandbox-id>.$CUBE_DOMAIN"
echo "  应返回 $CUBE_SANDBOX_IP"
